# Generated by Django 4.0.5 on 2024-08-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='official_tag',
            field=models.ManyToManyField(blank=True, to='gallery.officialtag'),
        ),
    ]
