# Generated by Django 4.0.5 on 2024-08-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_officialtag_image_official_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('age', 'Age'), ('body', 'Body'), ('ethnicity', 'Ethnicity')], default='default', max_length=100),
            preserve_default=False,
        ),
    ]
