# Generated by Django 4.0.5 on 2024-08-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('age', 'Age'), ('body', 'Body'), ('ethnicity', 'Ethnicity'), ('interest', 'Interest')], max_length=100),
        ),
    ]
