# Generated by Django 4.0.5 on 2024-08-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
    ]
