# Generated by Django 4.0.5 on 2024-08-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_image_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='full_image_url',
            field=models.URLField(default='http://example.com/default.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='gallery_image_url',
            field=models.URLField(default='http://example.com/default.jpg'),
            preserve_default=False,
        ),
    ]
