# Generated by Django 4.0.5 on 2024-08-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_image_gallery_image_remove_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='full_image_url',
            field=models.URLField(default='https://via.placeholder.com/512'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery_image_url',
            field=models.URLField(default='https://via.placeholder.com/512'),
        ),
    ]
