# Generated by Django 4.0.5 on 2024-08-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_image_full_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default', upload_to='gallery_images/'),
            preserve_default=False,
        ),
    ]
