# Generated by Django 4.0.5 on 2024-08-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='gallery_images/default.jpg', upload_to='gallery_images/'),
        ),
    ]
