# Generated by Django 4.0.5 on 2024-08-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery_image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
    ]
