# Generated by Django 4.0.5 on 2024-08-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_image_full_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='full_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='gallery_image_url',
            field=models.URLField(default='https://via.placeholder.com/512', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
